name: Charge The Globe
layout_spectrum: 0.7335
typography_spectrum: 0.90609
cta: {}
analytics: {}
opengraph: {}
color:
  brandColors:
    - '#ffffff'
    - '#c792aa'
    - '#026472'
    - '#784625'
    - '#f87505'
  brandStrength: 0.504446889506653
  lightness: 0.2204755067359656
  saturation: 0.2893924838863313
  rhythmicContrast: 0.6349660221021622
purpose: []
title: Charge The Globe
author:
  name: Jenny Marsden
  email: chargetheglobe@gmail.com
