layout_spectrum: 0.15492197452113032
typography_spectrum: 0.10702311364002526
color:
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
  brandStrength: 0.4308985769748688
  lightness: 0.029224376194179058
  saturation: 0.9656230721157044
  rhythmicContrast: 0.17175386799499393
opengraph: {}
analytics: {}
author:
  name: Jenny Marsden
  email: chargetheglobe@gmail.com
name: Charge The Globe
cta: {}
navigation:
  - name: Photo Of The Week
    url: 'http://www.chargetheglobe.com/photo-of-the-week'
    type: external
title: Charge The Globe
description: 'One womans journey to the end of the earth: and hopefully back!'
purpose: []
