name: Charge The Globe
favicon: null
layout_spectrum: 0.7335
typography_spectrum: 0.90609
author:
  name: Jenny Marsden
  email: chargetheglobe@gmail.com
title: Charge The Globe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c792aa'
    - '#026472'
    - '#784625'
    - '#f87505'
  brandStrength: 0.504446889506653
  lightness: 0.2204755067359656
  saturation: 0.2893924838863313
  rhythmicContrast: 0.6349660221021622
purpose: []
