typography_spectrum: 0.90609
color:
  brandColors:
    - '#ffffff'
    - '#c792aa'
    - '#026472'
    - '#784625'
    - '#f87505'
  brandStrength: 0.504446889506653
  lightness: 0.2204755067359656
  saturation: 0.2893924838863313
  rhythmicContrast: 0.6349660221021622
opengraph: {}
layout_spectrum: 0.7335
analytics: {}
author:
  name: Jenny Marsden
  email: chargetheglobe@gmail.com
name: Charge The Globe
cta: {}
navigation:
  - name: Photo Of The Week
    url: 'http://www.chargetheglobe.com/photo-of-the-week'
    type: external
title: Charge The Globe
description: 'One womans journey to the end of the earth: and hopefully back!'
purpose: []
